### ISSUE TITLE
missing working example from scratch

### ISSUE THREAD

**Issue by jgrzebyta** [fhuttner/buffalo#3]
Hi,

I am trying to build parser for Turtle RDF format and I created `.y` file according the specification.

I tried to "compile" it into `.lisp` file using `build-grammar-from-yacc` function but I have error that:

```
:/* (value NIL). Expected one of: (:START
                                                       :LEFT
                                                       :RIGHT
                                                       :NONASSOC
                                                       :TOKEN)
```

It seems that semantics from `bnf.lex` file are not taken into account. Should I compile anything more with `gcc` or another compiler? I do not know neither C nor yacc. I have just simply recreated rules using `cgrammar.y` as a template.

**Comment by fhuttner** [comment]
You have to have a lex-compatible lexer available to make this work (flex is a fine free one) and also a C compiler like gcc. Then, in a shell in your working directory, type:
```
$  flex bnf.lex
$  gcc -o bnf lex.yy.c
$  cat mygrammar.y| ./bnf >mygrammar.txt
```
Then in your REPL you can import the tokenized grammar like
```lisp
(build-grammar-from-yacc 'mygrammar "mygrammar.txt")
```
As an alternative, if you have GNU Bison (the free version of yacc) you can produce xml output from your grammar. Again in the shell:
```
$  bison --xml=mygrammar.xml mygrammar.y
```
In Common Lisp, you need the s-xml package (e.g. via quicklisp) and [bison2buffalo](https://github.com/fhuttner/buffalo-testsuite/blob/master/bison2buffalo.lisp):
```lisp
(bison2buffalo:read-grammar 'mygrammar "mygrammar.xml")
```

**Comment by jgrzebyta** [comment]
Thanks a lot. It would be worth to add that explanation into html manual
file.
